export default {
    id: "tukpjtucg",
    completed: false,
    children: [
      {
        text: "What is this?",
        id: "xlhueplvhc",
        children: [
          {
            text: "It's a clone of a popular app called Workflowy",
            id: "orufxxowvt",
            children: [
              {
                text: "What is Workflowy?",
                id: "pyvl",
                children: [
                  {
                    text: "Basically what you're seeing here",
                    id: "jginukt",
                    children: [],
                    completed: false,
                    description: "",
                    open: true,
                  },
                  {
                    text: "Coming soon:",
                    id: "vlhekkhyh",
                    children: [
                      {
                        text: "mirror items",
                        id: "rpkqtwnja",
                        children: [],
                        completed: false,
                        description: "",
                        open: true,
                      },
                      {
                        text: "Add links, formatting toolbar",
                        id: "ljgfuczcn",
                        children: [],
                        completed: false,
                        description: "",
                        open: true,
                      },
                      {
                        text: "Corner click menus",
                        id: "magpdsz",
                        children: [],
                        completed: false,
                        description: "",
                        open: true,
                      },
                      {
                        text: "Parse exported items from workflowy",
                        id: "xntpyxib",
                        children: [],
                        completed: false,
                        description: "",
                        open: true,
                      },
                    ],
                    completed: false,
                    description: "",
                    open: true,
                  },
                  {
                    text: "Why?",
                    id: "adewrnpl",
                    children: [
                      {
                        text: "I was bored",
                        id: "wycremrdh",
                        children: [],
                        completed: false,
                        description: "",
                        open: true,
                      },
                    ],
                    completed: false,
                    description: "",
                    open: true,
                  },
                ],
                completed: false,
                description: "",
                open: false,
              },
            ],
            completed: false,
            description: "Workflowy isn't open source. Which annoys me",
            open: true,
          },
          {
            text: "Who made it?",
            id: "vsjjyvn",
            children: [
              {
                text: "@Explosion-Scratch",
                id: "mbrfqyvk",
                children: [],
                completed: false,
                description: "",
                open: true,
              },
            ],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "Click the home button in the header to see more!",
            id: "home",
          },
        ],
        completed: false,
        description: "",
        open: true,
      },
      {
        text: "How do I use it?",
        id: "ivvhql",
        children: [
          {
            text: "Just type basically",
            id: "vqrioja",
            children: [],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "Hit enter to create a new bullet point",
            id: "dwkdpdobsj",
            children: [
              {
                text: "Hover over the bullet icon of a bullet point to collapse it",
                id: "igaitpi",
                children: [],
                completed: false,
                description: "",
                open: true,
              },
            ],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "Press tab to indent an item",
            id: "azozdsc",
            children: [
              {
                text: "Press Shift + Tab to undo it",
                id: "vruwdrvhhf",
                children: [],
                completed: false,
                description: "",
                open: true,
              },
            ],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "Click on the menu up top to navigate back to the main notes!",
            id: "quaw",
            children: [],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "Use shift + enter to add a description",
            id: "gkdjyurwse",
            children: [
              {
                text: "Press shift + enter again to go back to editing bullet points",
                id: "enwefxnd",
                children: [],
                completed: false,
                description: "",
                open: true,
              },
            ],
            completed: false,
            description: "Like this",
            open: true,
          },
        ],
        completed: false,
        description: "",
        open: false,
      },
      {
        text: "Show me some features!",
        id: "dalmdwc",
        children: [
          {
            text: "It's rich HTML so you can use <b>bold</b>&nbsp;and <i>italic</i>&nbsp;text",
            id: "atlmloojt",
            children: [],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "You can collapse items by clicking on the arrow new to the bullet point",
            id: "dipzengk",
            children: [],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: 'You can "zoom" to items by clicking on the bullet point',
            id: "tvdsgndh",
            children: [],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "You can add descriptions with Shift + enter",
            id: "lfobtj",
            children: [],
            completed: false,
            description: "",
            open: true,
          },
          {
            text: "You eventually will be able to toggle the style of the bullet points",
            id: "tialrbnq",
            children: [
              {
                text: "Like this checkbox!",
                id: "maypdcfsvd",
                children: [],
                display: "checkbox",
                completed: false,
                description: "",
                open: true,
              },
            ],
            completed: false,
            description: "",
            open: true,
          },
        ],
        completed: false,
        description: "",
        open: true,
      },
    ],
    open: true,
  };